name: Publish Docker
on: [push]
jobs:
  build-x86:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        file: Dockerfile
        push: true
        tags: ghcr.io/${{ github.actor }}/unraidapi:latest
        platforms: linux/amd64
  build-arm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        file: DockerfilePI
        push: true
        tags: ghcr.io/${{ github.actor }}/unraidapi:arm
        platforms: linux/arm64,linux/arm
